services:
  app:
    build: .
    environment:
      - NEF_ADDRESS=${NEF_ADDRESS}
      - NEF_USER=${NEF_USER}
      - NEF_PASSWORD=${NEF_PASSWORD}
      - PATH_TO_CERTS=${PATH_TO_CERTS}
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
      - CAPIF_PORT_HTTP=${CAPIF_PORT_HTTP}
      - CAPIF_PORT_HTTPS=${CAPIF_PORT_HTTPS}
      - CALLBACK_ADDRESS=${CALLBACK_ADDRESS}
    container_name: zorte_netapp
    extra_hosts:
      - capifcore:${CAPIF_IP}
    ports:
      - "5000:5000"
    restart: unless-stopped
