apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zortenet.fullname" . }}
  labels:
    {{- include "zortenet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zortenet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zortenet.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: zortenet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn", "zortenet.app:app", "--host", "0.0.0.0", "--port", "{{ .Values.service.port }}"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "zortenet.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
